package ai.careerforge.application.domain;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

/**
 * Immutable — one per generation, versioned per {@link Application}, mirroring resume-service's
 * {@code ResumeVersion} (docs/DATABASE.md &sect;3, ARCHITECTURE_DECISIONS.md ADR-019).
 *
 * <p>{@code subject} and the greeting/closing/sign-off frame of {@code body} are assembled
 * deterministically by {@code EmailGenerationService} from already-verified data (the
 * application's job title/company, the candidate's own stated name) — never generated by the
 * model. Only {@code highlights} is model output, and it is stored here purely for audit
 * traceability; {@code body} is the single field the UI renders and the user copies.
 */
@Document(collection = "emails")
public class EmailContent {

    @Id
    private String id;

    @Field("applicationId")
    private String applicationId;

    @Field("userId")
    private String userId;

    @Field("version")
    private int version;

    @Field("subject")
    private String subject;

    @Field("body")
    private String body;

    /** Model-generated, grounded paragraph(s) that fed into {@code body} — kept for audit
     *  traceability; each entry is {@code {text, evidenceIds}}. */
    @Field("highlights")
    private List<Map<String, Object>> highlights;

    @Field("groundingReport")
    private Map<String, Object> groundingReport;

    @Field("removedParagraphs")
    private List<String> removedParagraphs;

    @Field("promptVersion")
    private String promptVersion;

    @Field("modelId")
    private String modelId;

    @CreatedDate
    @Field("createdAt")
    private Instant createdAt;

    protected EmailContent() {
        // Spring Data
    }

    public EmailContent(String applicationId, String userId, int version, String subject, String body,
                        List<Map<String, Object>> highlights, Map<String, Object> groundingReport,
                        List<String> removedParagraphs, String promptVersion, String modelId) {
        this.applicationId = applicationId;
        this.userId = userId;
        this.version = version;
        this.subject = subject;
        this.body = body;
        this.highlights = highlights;
        this.groundingReport = groundingReport;
        this.removedParagraphs = removedParagraphs;
        this.promptVersion = promptVersion;
        this.modelId = modelId;
    }

    public String id() {
        return id;
    }

    public String applicationId() {
        return applicationId;
    }

    public String userId() {
        return userId;
    }

    public int version() {
        return version;
    }

    public String subject() {
        return subject;
    }

    public String body() {
        return body;
    }

    public List<Map<String, Object>> highlights() {
        return highlights;
    }

    public Map<String, Object> groundingReport() {
        return groundingReport;
    }

    public List<String> removedParagraphs() {
        return removedParagraphs;
    }

    public Instant createdAt() {
        return createdAt;
    }
}
